<?php

namespace Eight\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends EntityRepository
{
    public function getNextPosition($subject, $id, $type = 'default')
    {
        $q = $this->createQueryBuilder('b');

        $q
            ->select('b.seq')
            ->where('b.type = :type')
            ->orderBy('b.seq', 'DESC')
            ->setMaxResults(1)
            ->setParameters(array(
                'type' => $type
                ))
            ;

        $current = $q->getQuery()->getScalarResult();

        if (count($current)) {
            $next = (int) $current[0]['seq'];
            return $next + 1;
        }

        return 0;
    }
}
