<?php

namespace Eight\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    public function reorder($ids)
    {
        if (count($ids) == 0) {
            return;
        }

        $counter = 0;
        foreach ($ids as $id) {
            $this->find($id)->setPosition($counter);
            $counter++;
        }

        $this->_em->flush();
    }

    public function findOneByTag($tag)
    {
        $q = $this->createQueryBuilder('p');
        $q
            ->select('p')
            ->leftJoin('p.tags', 't')
            ->where('t.name = :name')
            ->setParameter('name', $tag)
            ;
        return $q->getQuery()->getOneOrNullResult();
    }

    public function getByTag($tag)
    {
        return $this->findOneByTag($tag);
    }

    public function findI18nPage($tag, $locale)
    {
        $i18nTag = $tag . '.' . $locale;

        $q = $this->createQueryBuilder('p');
        $q
            ->select('p')
            ->leftJoin('p.tags', 't')
            ->where('t.name = :name')
            ->setParameter('name', $i18nTag)
            ;
        return $q->getQuery()->getOneOrNullResult();
    }

    public function findPagesByLocale($locale)
    {
        $q = $this->createQueryBuilder('p');
        $q
            ->select('p')
            ->leftJoin('p.route', 'r')
            ->where('r.locale = :locale')
            ->setParameter('locale', $locale)
            ;
        return $q->getQuery()->getResult();
    }
}
